version: "3"
services:
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=test123
            - MYSQL_DATABASE=oauth
        ports:
            - "3306:3306"

    oauth:
        image: oauth:latest
        build:
            context: ./
        environment:
            - FOO=bar
        ports:
            - "8080:8080"

