version: "3"
services:
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=test123
            - MYSQL_DATABASE=oauth
            - GIN_MODE=release
        ports:
            - "3306:3306"
        volumes:
            - data:/var/lib/mysql

    oauth:
        image: oauth:latest
        build:
            context: ./
        ports:
            - "8080:8080"

volumes:
    data:
